### ISSUE TITLE
KAS support?

### ISSUE THREAD

**Issue by Schlumpf** [OE4T/tegra-demo-distro#121]
Hi,
this repo is currently based on git submodules. Are there any plans to support [kas](https://github.com/siemens/kas) in future?

best regards
Schlumpf

**Comment by madisongh** [comment]
No plans, but if someone wants to use it and finds there's something we could do to make it easier to use with the layers here, I'd be open to discussing that.

**Comment by Schlumpf** [comment]
OK, thanks for the answer.
I got it to work with kas without any changes to this repository.

**Comment by outbackdingo** [comment]
ok can you provide simple steps on how you did it ?
