### ISSUE TITLE
There is no MB1-BCT device type corresponding to pt type: 9

### ISSUE THREAD

**Issue by lorienberne** [OE4T/tegra-demo-distro#155]
Hello,

I am trying to change the partition layout to use NVME but I am getting this error:

```
| [   1.3744 ]
| [   1.3744 ] Parsing config file :tegra19x-mb1-bct-device-qspi-p3668.cfg
| [   1.3744 ] Added Platform Config 9 data with size :- 40
| [   1.3744 ]
| [   1.3744 ] Updating mb1-bct with firmware information
| [   1.3766 ] tegrabct_v2 --chip 0x19 --mb1bct mb1_cold_boot_bct_MB1.bct --updatefwinfo flash.xml.bin
| [   1.3774 ] MB1-BCT version: 0x1
| [   1.3802 ]
| [   1.3802 ] Updating mb1-bct with storage information
| [   1.3821 ] tegrabct_v2 --chip 0x19 --mb1bct mb1_cold_boot_bct_MB1.bct --updatestorageinfo flash.xml.bin
| [   1.3828 ] MB1-BCT version: 0x1
| [   1.3830 ] There is no MB1-BCT device type corresponding to pt type: 9
| [   1.3873 ]
| Error: Return value 2
| Command tegrabct_v2 --chip 0x19 --mb1bct mb1_cold_boot_bct_MB1.bct --updatestorageinfo flash.xml.bin
| WARNING: exit code 1 from a shell command.
| 
```

I have modified flash_mender.xml via a patch to replace the device type like this:

```
--- ../flash_mender.xml    2021-09-25 18:51:12.112779029 +0200
+++ ../flash_mender.xml        2021-09-25 18:56:35.133990639 +0200
@@ -498,7 +498,7 @@
               device. </description>
         </partition>
     </device>
-    <device type="sdcard" instance="0" sector_size="512" num_sectors="33554432">
+    <device type="nvme" instance="0" sector_size="512" num_sectors="33554432">
         <partition name="master_boot_record" type="protective_master_boot_record">
             <allocation_policy> sequential </allocation_policy>
             <filesystem_type> basic </filesystem_type>
```

Does this make sense? Is using NVME supported with yocto (it is with jetpack)? If it is not supported can you guide me where should I make modifications to supported so I can submit a PR?

**Comment by dwalkes** [comment]
> Is using NVME supported with yocto (it is with jetpack)?

NVMe is definitely supported as a storage option, but I think you are asking if you can boot from it and flash it as an alternative to using eMMC.

I don't have personal experience with this, perhaps others here do.  [This post](https://forums.developer.nvidia.com/t/tegraflash-nvme-support/170278) on the forum looks like it might be related, looks like there are some important limitations about booting from NVMe on Xavier.

One option you could consider is keeping your A/B rootfs on emmc and using NVMe for a `/data` partition.  That works for us and simplifies things because you can still keep the boot code on emmc which has a bit more history and probably is better tested/supported.

**Comment by lorienberne** [comment]
Thank you for your fast reply! 

Yes, I am looking to boot from NVMe. Our image ends up taking to much space and doesn't fit in the emmc. I was looking to move the rootfs to NVMe while keeping mender OTA updates functionality. As far as I know fFrom 32.6.1 onwards booting from NVMe is officially supported by NVDIA. Does this also apply to yocto images with mender? Where should I look in to?

**Comment by dwalkes** [comment]
> Does this also apply to yocto images with mender?

I don't know of anyone using this yet, so you are probably going to be blazing a new trail.

> Where should I look in to?

If you haven't already I'd start by getting the stock distribution working with NVIDIA's instructions.  As mentioned above, it looks like there are some limitations you need to understand.  Once you understand the deployment status on NVIDIA stock L4T you can likely understand what, if anything, is different with the yocto sources.

**Comment by lorienberne** [comment]
I will write any discoveries I make.

Thank you for the support.

**Comment by ichergui** [comment]
Hello @lorienberne 

Is there any updates about this issue ? otherwise, I will close it

**Comment by ichergui** [comment]
I will close this issue since there is no updates.
Feel free to reopen new issue

**Comment by madisongh** [comment]
Should also note that we do now support initrd flashing to boot off an external drive - see [this wiki page](https://github.com/OE4T/meta-tegra/wiki/initrd-flashing-support) for more info.
