### ISSUE TITLE
No UVC Camera and IWLWIFI

### ISSUE THREAD

**Issue by ierturk** [OE4T/tegra-demo-distro#174]
Hi,

I already tried all demo images on Jetson Nano Devkit as described in the READ.ME. I have an Intel 8265 on M.2 interface and a UVC camera on USB. However there is no video device and no wifi/bluetooth device listed anywhere. I checked kernel config (`bitbake -c menuconfig virtual/kernel`) and the modules seems to be enabled. However there is no kernel module under `/lib/modules/4.9.253-l4t-r32.6+gf8935b85523e/kernel/net/wireless`.

How do I enable the UVC camera and the wireless module?

`lsusb` output
```
Bus 002 Device 002: ID 0bda:0411 Realtek Semiconductor Corp. Hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 003: ID 8087:0a2b Intel Corp. Bluetooth wireless interface
Bus 001 Device 006: ID 17ef:608d Lenovo Optical Mouse
Bus 001 Device 005: ID 17ef:608c Lenovo Lenovo Calliope USB Keyboard
Bus 001 Device 004: ID 046d:0825 Logitech, Inc. Webcam C270
Bus 001 Device 002: ID 0bda:5411 Realtek Semiconductor Corp. RTS5411 Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

`lspci` output
```
00:01.0 PCI bridge: NVIDIA Corporation Device 0fae (rev a1)
00:02.0 PCI bridge: NVIDIA Corporation Device 0faf (rev a1)
01:00.0 Network controller: Intel Corporation Wireless 8265 / 8275 (rev 78)
02:00.0 Ethernet controller: Realtek Semiconductor Co., Ltd. RTL8111/8168/8411 PCI Express Gigabit Ethernet Controller (rev 15)

```
`lsmod` output
```
Module                  Size  Used by
overlay                57776  0
nvgpu                1896634  13
fuse                  125841  1
```

Thanks in advance.
Ibrahim

**Comment by madisongh** [comment]
Just add the needed kernel modules to your image.  If you know that just those two are needed, then putting
```
CORE_IMAGE_EXTRA_INSTALL = "kernel-module-iwlwifi kernel-module-uvcvideo"
```
in your `local.conf` should be enough.  If there are other kernel modules that you might need, you could just use
```
CORE_IMAGE_EXTRA_INSTALL = "kernel-modules"
```
to have all kernel modules included in the image.

**Comment by ierturk** [comment]
Thanks for prompt reply. Now uvc camera is up. But iwlwifi has some error. I get the info from dmesg as follow
```
root@jetson-nano-devkit:~# dmesg | grep iwl
[   11.267537] iwlwifi 0000:01:00.0: enabling device (0000 -> 0002)
[   11.269642] iwlwifi 0000:01:00.0: Direct firmware load for iwlwifi-8265-26.ucode failed with error -2
[   11.269645] iwlwifi 0000:01:00.0: Falling back to user helper
[   72.819169] iwlwifi 0000:01:00.0: Direct firmware load for iwlwifi-8265-25.ucode failed with error -2
[   72.819201] iwlwifi 0000:01:00.0: Falling back to user helper
```

**Comment by madisongh** [comment]
Sounds like you need to include the needed firmware in your image, too, doesn't it? There is a `linux-firmware-iwlwifi-8265` package available which might provide what you need.

**Comment by ierturk** [comment]
hi @madisongh,

Thanks for your great support. I also added some extra code and it seems to be OK now.
```
IMAGE_INSTALL:append = " linux-firmware-iwlwifi-8265"
IMAGE_INSTALL:append = " kernel-module-iwlwifi"
IMAGE_INSTALL:append = " kernel-module-iwlmvm"
IMAGE_INSTALL:append = " kernel-module-iwldvm"
IMAGE_INSTALL:append = " kernel-module-uvcvideo"
```
I have just one more question how to get the command `nmcli`. I added extra packahe as follow bot no command found `nmcli`.
```
IMAGE_INSTALL:append = " networkmanager" 
IMAGE_INSTALL:append = " modemmanager"
PACKAGECONFIG:append_pn-networkmanager = " nmcli"
```
Regards,
Ibrahim

**Comment by ierturk** [comment]
Hi @madisongh, I added the command `nmcli` as follow. Everything  seems to be OK. I have just a problem the module. Initialization take some time then usual because of the system try all `ucode`s from 26 to 22. For now we can close the issue.

IMAGE_INSTALL:append = " networkmanager-nmcli"

Thanks again.
Ibrahim
