### ISSUE TITLE
Docker not working properly in tegra-demo-distro-image-full (Honister)

### ISSUE THREAD

**Issue by ddbabich** [OE4T/tegra-demo-distro#177]
Hi, I followed the instructions for creating a custom distro using the Honister branch for a TX2i.  When I try running docker containers I get a somewhat ambiguous error.  So I thought perhaps I did something wrong in my own distro.  I wen't back to the tegra-demo-distro demo-image-full with no changes and installed it on my TX2i.  I receive the same error while attempting to run the container:

```
audit: type=1701 audit(1638380233.899:35): auid=4294967295 uid=0 gid=0 ses=4294967295 pid=6460 comm="nvc:[driver]" exe="/usr/bin/nvidia-container-cli" sig=11
docker: Error response from daemon: failed to create shim: OCI runtime create failed: container_linux.go:380: starting container process caused: process_linux.go:545: container init caused: Running hook #0:: error running hook: exit status 1, stdout: , stderr: nvidia-container-cli: initialization error: driver error: failed to process request: unknown.
```
I've tried several different containers and I always get this same error.  I've attached the output from ```journalctl -b -u docker.service``` as well.  Any ideas?
Thanks
-David
[docker-fail-log.txt](https://github.com/OE4T/tegra-demo-distro/files/7636067/docker-fail-log.txt)

**Comment by madisongh** [comment]
At what revision is your meta-tegra submodule?  That looks like an issue that was fixed with [this commit](https://github.com/OE4T/meta-tegra/commit/2ebbd54ccc48cba5dfaa74a54f7acc7de105fb55#diff-97a31023ba3ada2059420c1fce7a90c39ee5a82f01e10d39ab480523ac80ff3d), so make sure you're at least at that commit or later.

**Comment by ddbabich** [comment]
Ah, yes I haven't updated that layer in a while.  I'm on the honister branch commit:
5fd61c425b16cf028a17245d7dfaa82c44d879c3
which just happens to be one commit prior to the commit you linked :1st_place_medal: 

Sorry about that, not sure why I didn't think to try and update...

I'll give it a try
Thanks!

**Comment by ddbabich** [comment]
Yes that fixed it!  Thanks again for the help, glad that was an easy one.
