### ISSUE TITLE
Mender Image Upgrade failed (bootloader update error)

### ISSUE THREAD

**Issue by damgot** [OE4T/tegra-demo-distro#190]
Hello, I'm trying to upgrade my Jetson nano (with a yocto image) trought mender.
So I've uploaded my .mender image on my mender server and programmed a release for my device.

The upgrade process start fine but I rapidly got an error :
Feb 11 10:46:37 jetson-nano-qspi-sd mender[4710]: time="2022-02-11T10:46:37Z" level=info msg="Executing script: ArtifactInstall_Leave_80_bl-update"
Feb 11 10:46:37 jetson-nano-qspi-sd mender[4710]: time="2022-02-11T10:46:37Z" level=info msg="Collected output (stderr) while running script /var/lib/mender/scripts/ArtifactInstall_Leave_80_bl-update\nERR: cannot perform bootloader update\n\n---------- end of script output"

I tried to run the tegra-bootloader-update manually, but here I've the following error : 
Error: missing entries for partitions: BCT, RP1, PT, VER, DTB, LNX
       for TNSPEC 3448-401-0000-B.0-1-0-jetson-nano-qspi-sd-mmcblk0p1

I really don't know how to fix that. Do you have any idea ?

Thanks

**Comment by ichergui** [comment]
Hello,

**Comment by ichergui** [comment]
I will check later and will keep updated.

**Comment by madisongh** [comment]
This looks like the source of the problem: `TNSPEC 3448-401-0000-B.0-1-0-jetson-nano-qspi-sd-mmcblk0p1`

The `401` is a recent board revision (aka FAB), and the BUP payload generator isn't including entries for that.

Assuming it boots and runs OK when you flash it via USB, you can just work around the problem by adding:
```
TEGRA_BUPGEN_SPECS_append_jetson-nano-qspi-sd = " fab=401"
```
to your build configuration (e.g., to `$BUILDDIR/conf/local.conf`).

**Comment by ichergui** [comment]
Hey guys,

I push a [PR](https://github.com/OE4T/meta-tegra/pull/898) to master branch of `meta-tegra` to add support for the new FAB.
Will back ported to the appropriate branches once this one is merged.

**Comment by damgot** [comment]
Hello.
A Big thanks for your very fast support. It works perfectly. Just adding the fab 401 in my local.conf solved the problem. 
Thanks a lot !
