### ISSUE TITLE
td-initramfs

### ISSUE THREAD

**Issue by llewellyn-evo** [OE4T/tegra-demo-distro#215]
Hi 

I can't seem to find any information about this. I am trying to use SW update and A/B support on branch dunfell-l4t-r32.5.0 and I get the error no buildable providers for td-initramfs. Any help would be appreciated. 

Thanks

**Comment by madisongh** [comment]
There is no `td-initramfs` recipe in this distro (nor support for `swupdate`). I have a demo of `swupdate` support in [my test distro](https://github.com/madisongh/tegra-test-distro), which was forked off this one, and that has the `td-initramfs` recipe.
