### ISSUE TITLE
meta-mender-commercial failed with kirkstone branch

### ISSUE THREAD

**Issue by Gandouge78** [OE4T/tegra-demo-distro#218]
Hi,

I try to update my current distro from dunfell to kirkstone.
We use mender-delta-binary and I have some issue with the meta-mender repository.
It seems that the receipts in meta-mender-commercial are not compatible with kirkstone.

For now i will create a fork on my account an try to fix it  but do you have an idea of when you will make the change ?

`ERROR: Variable EXTRA_IMAGECMD_ext4_append file: /home/DockerUser/working_directory/workspace/BXT4_folder/BXT4/layers/meta-mender-commercial/conf/layer.conf line: 20 contains an operation using the old override syntax. Please convert this layer/metadata before attempting to use with a newer bitbake.`

**Comment by ichergui** [comment]
Hello @Gandouge78 
We didn't work yet on the update mechanism (using `mender`).
You should open an issue in the [mender](https://github.com/madisongh/meta-mender) and ask them about `kirkstone`  because it doesn't exists in both `meta-mender` and `meta-mender-community`

**Comment by dwalkes** [comment]
> We didn't work yet on the update mechanism (using mender).

One clarification here - kirkstone branch should be working for Jetpack 4.6 on https://github.com/oe4t/tegra-demo-distro/tree/kirkstone for `tegrademo-mender` using https://github.com/mendersoftware/meta-mender-community/tree/kirkstone-next.  I haven't tried any recipe in meta-mender-commercial, however, and this is something you should bring up with Mender.

**Comment by ichergui** [comment]
Thanks @dwalkes for the clarification.

I didn't try `kirkstone` with `L4T R32.7.2 / JetPack 4.6.2`

**Comment by Gandouge78** [comment]
Thanks for the answer.
Yes tegrademo-mender is working perfectly. 
The problem is when you add mender-binary-delta or mender-monitor to tegrademo-mender.
I will look into mender repo and ask them

**Comment by madisongh** [comment]
I think I just converted meta-mender-core to use the new overrides syntax for our kirkstone-compatible fork of the meta-mender repository, since that's all we use here.

**Comment by Gandouge78** [comment]
Ok thanks @madisongh 
It's what I observed.
I make the change in a fork of mine and it's working perfectly
