### ISSUE TITLE
Error running bitbake image-full 

### ISSUE THREAD

**Issue by ACAVJW4H** [OE4T/tegra-demo-distro#22]
I am getting the following fatal error when trying to bitbake image-full
 `repository '/home/mete/tegra-demo distro/build/downloads/git2/github.com.opencv.opencv_3rdparty.git/' does not exist` 
`opencv-4.1.0-r0 do_unpack: Fetcher failure: Fetch command export PSEUDO_DISABLED=1; unset _PYTHON_SYSCONFIGDATA_NAME; export DBUS_SESSION_BUS_ADDRESS="unix:path=/run/user/1000/bus";`

I looked around the opencv_3rd party repo and its a strange repo with a placeholder master branch and code divided into different branches. Could it be related to that? Can we skip building examples requiring 3rd_party?

**Comment by madisongh** [comment]
It looks like you have a blank in the top-level directory name for your workspace, based on the path name reported in the error: `/home/mete/tegra-demo distro/`. Spaces in path names can confuse the tools, and that may be what's happening here.  Try a different path name with no spaces in any of the directory name(s).

**Comment by ACAVJW4H** [comment]
I was actually following a tutorial and my local repo was already on the  dunfell-l4t-r32.4.3 branch. I don't think the error was caused by the space, I might have introduced the space while copying from the terminal. (This step is actually far into the build like 3-4 hours in on my poor nuc) On an other note `bitbake base-image-egl `was successful in the same folder

**Comment by madisongh** [comment]
Can you attach the `log.do_unpack` file, so we can see the full log with the actual error message being logged?

**Comment by ACAVJW4H** [comment]
I installed a fresh ubuntu and was able to produce the image. I guess it failed to download one of the many gigs of files needed to reach image-full. Thanks for the support though
