### ISSUE TITLE
Error running bitbake image-sato

### ISSUE THREAD

**Issue by ACAVJW4H** [OE4T/tegra-demo-distro#23]
I am getting the following error and cant build the image 

```
ERROR: Nothing RPROVIDES 'vulkan-demos' (but /home/mete/tegra-demo-distro/layers/meta-tegrademo/recipes-demo/packagegroups/packagegroup-demo-vulkantests.bb RDEPENDS on or otherwise requires it)

NOTE: Runtime target 'vulkan-demos' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['vulkan-demos']
NOTE: Runtime target 'packagegroup-demo-vulkantests' is unbuildable, removing...
Missing or unbuildable dependency chain was: ['packagegroup-demo-vulkantests', 'vulkan-demos']

ERROR: Required build target 'demo-image-sato' has no buildable providers.
Missing or unbuildable dependency chain was: ['demo-image-sato', 'packagegroup-demo-vulkantests', 'vulkan-demos']
```

**Comment by madisongh** [comment]
This should be fixed now.  You may run into other issues building the demo distro from the master branch, though, and unless you need to work with the bleeding edge, you would be better off using the [dunfell-l4t-r32.4.3](https://github.com/OE4T/tegra-demo-distro/tree/dunfell-l4t-r32.4.3) branch.

**Comment by dwalkes** [comment]
@madisongh should we change the default branch on tegra-demo-distro to dunfell-l4t-r32.4.3?  Another option might be a comment in the readme linking back to https://github.com/OE4T/meta-tegra/wiki/Which-branch-should-I-use%3F and I could add that.  It might be nice to add more cross linking to the meta-tegra project and Wiki.

**Comment by madisongh** [comment]
The README update sounds good to me, even if it's just listing the available branches we have in the demo distro and current usage recommendations.

**Comment by dwalkes** [comment]
See what you think about https://github.com/OE4T/tegra-demo-distro/pull/25/files - I tried to mirror what meta-tegra is doing with a reference to a wiki page and mentioned this in the setup steps.
