### ISSUE TITLE
failed to mounting ext4 file system using ext3 subsystem

### ISSUE THREAD

**Issue by gauravdhol** [OE4T/tegra-demo-distro#240]
Hi

I have prepare the tegraflash file using "bitbake demo-image-weston".
Build is successfully.
Now I have flash the SD card using "./dosdcard.sh", it is also success.

Now when I connect the SD Card to NVIDIA Tegra Jetson Xavier NX board, it is giving error
failed to mounting ext4 file system using ext3 subsystem
failed to mounting ext4 file system using ext2 subsystem

Can you please suggest what could be the problem?

Regards,

**Comment by madisongh** [comment]
Those messages can be safely ignored.  The kernel includes support for all three current versions of the ext filesystem (2, 3, and 4), and will try the earlier versions before ext4.

**Comment by gauravdhol** [comment]
thanks @madisongh for the feedback.

I am getting mounting error. please find attached error details.
Can you please help me to resolve this issue?

![image](https://user-images.githubusercontent.com/119558267/210199197-8a9b70fb-edab-4f2e-a94a-79141dbfafc6.png)

Regards,
Gaurav

**Comment by madisongh** [comment]
It looks like the APP partition on the SDcard didn't get written properly.  Can you check it on your host machine?  Use `sgdisk /dev/sdX --print` and `sgdisk /dev/sdX --verify` to check on the overall format and partition table, then use `fsck /dev/sdX1` to verify the APP partition's filesystem looks OK (using the actual device name for your SDcard reader in place of `/dev/sdX`).

**Comment by gauravdhol** [comment]
thanks @madisongh 

I have executed suggested commands, it seems like `sgdisk  /dev/sdX --print` and `sgdisk /dev/sdX --verify` command works as expected but `fsck /dev/sdX1` command has problem.

I did multiple attempts of writing of Mass-Storage using "sudo ./dosdcard.sh /dev/sdb" but all the time it is giving same problem for `fsck /dev/sdX1` 

![image](https://user-images.githubusercontent.com/119558267/210269003-00723716-0fa6-458a-a9b6-e3b998bd1dbf.png)

I am using Ubuntu 20.04 for build the OS and prepare the USB.

Please suggest how I can solve the problem

Regards,
Gaurav

**Comment by madisongh** [comment]
Try an `fsck` on the EXT4 filesystem image (should be `fsck demo-image-weston.ext4`).  If that fails, then something probably went wrong with unpacking the tegraflash package.... that can happen if you use a GUI-based tool to unpack the tarball, rather than using the `tar` command from a terminal window.

Once the filesystem image checks out OK, then try re-running the `dosdcard.sh` script, and before you remove the SDcard from the reader, do the `fsck /dev/sdb1`.  If that fails, then something went wrong with writing to the card, or possibly the card itself is bad.  If the `fsck` passes, use `eject /dev/sdb` to make sure that the card isn't in use, remove it from your host, and try it again in your Jetson.

**Comment by gauravdhol** [comment]
thanks @madisongh for the feedback.

I have extract using default GUI tools and tar command. I show few MBs difference in `demo-image-weston-jetson-xavier-nx-devkit.dataimg` and GBs of size difference into demo-image-weston.ext3

It seems like there is some issue while using GUI tools for extract.

I will re-perform activity by extracting using tar command and let you know the status.

thank you so much.

Regards,
Gaurav

**Comment by gauravdhol** [comment]
thank you @madisongh.

Problem is resolved. I am able to run image on EVK Kit.

to prepare SD card it took around 9 hours. Can you please suggest if we can prepare SD card quickly ?

Will close the ticket after your feedback

**Comment by madisongh** [comment]
There are tips on [the wiki page](https://github.com/OE4T/meta-tegra/wiki/Flashing-the-Jetson-Dev-Kit#for-sdcard-based-development-kits).

**Comment by gauravdhol** [comment]
thanks for the information. @madisongh 

after installing `bmap-tools` it is much much faster (flashing SDK card in 10 min)
