### ISSUE TITLE
package_write_rpm error.

### ISSUE THREAD

**Issue by leadercxn** [OE4T/tegra-demo-distro#247]
Hi OE4T developer, I met a probleam like this:  I want to install some files into my rootfs,  and I write a ac8265.bb file and build it into my image.bb,but when I build my project, it show some error like pic2.  I don't know the reason I have wrote `do_package_write_rpm[noexec] = "1"` in my bb file, it warned me to the mistakes.
<img width="1311" alt="image" src="https://user-images.githubusercontent.com/43691182/218355011-d5551aba-17f9-4782-8d98-3a23d57509f0.png">
<img width="1204" alt="image" src="https://user-images.githubusercontent.com/43691182/218355276-d2b531f4-26ac-4eb1-b6df-1b7ed3755913.png">

**Comment by madisongh** [comment]
The RPM packages are needed for constructing the rootfs, so you should not disable the execution of the packaging tasks in your recipe, or override the `do_package_write_rpm` function.

**Comment by leadercxn** [comment]
@madisongh Hi, I use `IMAGE_INSTALL += " kernel-modules  linux-firmware "` to install kernel modules and some firmware into rootfs. 
<img width="458" alt="image" src="https://user-images.githubusercontent.com/43691182/218688477-98ff5683-9f80-421e-aacf-9ce4030fc1ee.png">
