### ISSUE TITLE
build of deepstream 6.2 fails on branch kirkstone with target  jetson-agx-xavier-devkit

### ISSUE THREAD

**Issue by bbuce72** [OE4T/tegra-demo-distro#259]
Found issue when updating own distro to kirkstone, so checked build on tegra-demo-distro to verify where issue was.

To recreate:
```
    git clone https://github.com/OE4T/tegra-demo-distro.git
    cd tegra-demo-distro
    git checkout kirkstone
    git submodule update --init
    . ./setup-env --machine jetson-agx-xavier-devkit 
    bitbake deepstream-6.2
```

Error test:

```
    ERROR: deepstream-6.2-6.2.0-1-r0 do_package_qa: QA Issue: /opt/nvidia/deepstream/deepstream-6.2/lib/libnvds_riva_tts.so contained in package deepstream-6.2 requires libgrpc++.so.1.50()(64bit), but no providers found in RDEPENDS:deepstream-6.2? [file-rdeps]
    ERROR: deepstream-6.2-6.2.0-1-r0 do_package_qa: QA Issue: /opt/nvidia/deepstream/deepstream-6.2/lib/libnvds_riva_tts.so contained in package deepstream-6.2 requires libprotobuf.so.32()(64bit), but no providers found in RDEPENDS:deepstream-6.2? [file-rdeps]
```

**Comment by madisongh** [comment]
We have some [hacks in the recipe](https://github.com/OE4T/meta-tegra-community/blob/5a34aad96af5d0e9053656e38d113d9c0bdc5689/recipes-devtools/deepstream/deepstream-6.2_6.2.0-1.bb#L98-L109) to work around some SONAME/dependency issues with those prebuilt libraries.  Sounds like the hacks need to be updated to match the actual SONAMEs/versions for gRPC and protobuf.

**Comment by ichergui** [comment]
I will check that later today and update the branches. Sorry to see that happen to you @bbuce72

**Comment by bbuce72** [comment]
No worries, if i can assist with anything (this or otherwise) let me know. Was going to see if i could fix this one myself, but the hack looked like it was tied to grpc and protobuf from a different branch of open embedded, and figured you knew the easiest way to fix. Thanks for your efforts on this, makes Jetson development much easier.

**Comment by ichergui** [comment]
@bbuce72 I updated the deepstream 6.2 recipe. please try it and let me know if you have any issue

**Comment by bbuce72** [comment]
Thanks for the help. Built and flashed ok. Still need to get my distro updated (going from nano to AGX Xavier)  to see if the parts I use are ok. Will continue Tuesday.
Is there a regression test for deepstream/other tests other than my app to test more functionality?
Did see this message about a blacklisted component but for my purpose don't need audio. 

root@jetson-agx-xavier-devkit:~# gst-inspect-1.0 -b

(gst-plugin-scanner:1093): GStreamer-WARNING **: 01:28:00.224: Failed to load plugin '/usr/lib/gstreamer-1.0/deepstream/libnvdsgst_inferaudio.so': libnvds_audiotransform.so: cannot open shared object file: No such file or directory
Blacklisted files:
  libcustom2d_preprocess.so
  libnvdsgst_inferaudio.so

**Comment by dwalkes** [comment]
> Is there a regression test for deepstream/other tests other than my app to test more functionality?

I don't think we have a test defined in the [release validation](https://docs.google.com/spreadsheets/d/1EWG5QZvtWdk74gz48D4xCbegK-bsqMFJ8XOsyGdUUeI/edit#gid=1125662453) sheet for deepstream outside of the docker container today.  It would be great to add one.

**Comment by ichergui** [comment]
> Is there a regression test for deepstream/other tests other than my app to test more functionality? 

Yes, we do have a specific [recipe](https://github.com/OE4T/meta-tegra-community/blob/master/recipes-test/tegra-tests/deepstream-tests_1.0.bb) for deepstream tests

I tried it before merging the PR. Here is the result

```
nvstreammux: Successfully handled EOS for source_id=1
Frame Number= 1441 Number of Objects= 15 Vehicle_count= 12 Person_count= 3
Frame Number= 1441 Number of Objects= 0 Vehicle_count= 0 Person_count= 0
Frame Number= 1442 Number of Objects= 0 Vehicle_count= 0 Person_count= 0
End-of-stream
Exiting app

=== PASS:  py_deepstream_test3 ===
Tests run:     6
Tests passed:  6
Tests skipped: 0
Tests failed:  0
sh-5.1# 

```

If you have any comment please let me know.

**Comment by dwalkes** [comment]
Added a new row for deepstream tests in the [Release Validation](https://docs.google.com/spreadsheets/d/1EWG5QZvtWdk74gz48D4xCbegK-bsqMFJ8XOsyGdUUeI/edit#gid=1125662453) sheet.

**Comment by ichergui** [comment]
Closing this since fix was merged
