### ISSUE TITLE
Cannot run mender setup

### ISSUE THREAD

**Issue by ACAVJW4H** [OE4T/tegra-demo-distro#26]
I am not sure if  this the correct repo to ask this but I am trying to follow the mender on jetson nano tutorial. After a little head-scratching I was finally able to deploy the resulting images on to the nano and was greeted with a nice gui. 

I thought that since we define the tenant token in the build process my jetson would automagically show on my hosted.mender dashboard. Sadly there was nothing. The tutorials on the mender hub website did finish at that exact moment and didn't actually offer any next steps. Which I find very weird. It simply falls short to demonstrate that if you follow the steps you reach a fully working mender setup

So I did run systemctl status mender-client

`● mender-client.service - Mender OTA update service
     Loaded: loaded (/lib/systemd/system/mender-client.service; enabled; vendor preset: enabled)
     Active: active (running) since Sat 2000-01-01 01:13:02 UTC; 20 years 11 months ago
   Main PID: 4489 (mender)
      Tasks: 10 (limit: 4184)
     Memory: 18.5M
     CGroup: /system.slice/mender-client.service
             └─4489 /usr/bin/mender -daemon

Dec 10 23:49:45 jetson-nano-qspi-sd mender[4489]: time="2020-12-10T23:49:45Z" level=info msg="State transition: authorize-wait [Idle] -> authorize [Sync]"
Dec 10 23:50:05 jetson-nano-qspi-sd mender[4489]: time="2020-12-10T23:50:05Z" level=error msg="Failure occurred while executing authorization request: &url.Error{Op:\"Post\", URL:\"https://docker.mender.>
Dec 10 23:50:05 jetson-nano-qspi-sd mender[4489]: time="2020-12-10T23:50:05Z" level=error msg="Authorization request error: dial tcp: lookup docker.mender.io on 127.0.0.1:53: read udp 127.0.0.1:54533->12>
Dec 10 23:50:05 jetson-nano-qspi-sd mender[4489]: time="2020-12-10T23:50:05Z" level=error msg="Authorize failed: transient error: authorization request failed: generic error occurred while executing auth>
Dec 10 23:50:05 jetson-nano-qspi-sd mender[4489]: time="2020-12-10T23:50:05Z" level=info msg="State transition: authorize [Sync] -> authorize-wait [Idle]"
Dec 10 23:54:45 jetson-nano-qspi-sd mender[4489]: time="2020-12-10T23:54:45Z" level=info msg="State transition: authorize-wait [Idle] -> authorize [Sync]"
Dec 10 23:55:05 jetson-nano-qspi-sd mender[4489]: time="2020-12-10T23:55:05Z" level=error msg="Failure occurred while executing authorization request: &url.Error{Op:\"Post\", URL:\"https://docker.mender.>
Dec 10 23:55:05 jetson-nano-qspi-sd mender[4489]: time="2020-12-10T23:55:05Z" level=error msg="Authorization request error: dial tcp: lookup docker.mender.io on 127.0.0.1:53: read udp 127.0.0.1:46408->12>
Dec 10 23:55:05 jetson-nano-qspi-sd mender[4489]: time="2020-12-10T23:55:05Z" level=error msg="Authorize failed: transient error: authorization request failed: generic error occurred while executing auth>
Dec 10 23:55:05 jetson-nano-qspi-sd mender[4489]: time="2020-12-10T23:55:05Z" level=info msg="State transition: authorize [Sync] -> authorize-wait [Idle]"
`
2 things drew my attention somehow this process runs before NTP got a chance to get correct date. Thus if there was a need for certificate based communication it would fail.

On the other hand I believe this URL is not the correct one `URL:\"https://docker.mender.io/api/devices/v1/authentication/auth_requests\` I imagine it should be hosted.mender.io.. smthing.

So I tried to run mender setup which again failed because 
`ERRO[0000] Error checking write permissions to directory "/": open /temporaryFile267989584: read-only file system`

So I tried pointing mender with `mender setup -c /data/mender.conf` to the writable folder /data which gave me glimpse of hope after asking me for credentials. But my hope was quickly crushed with the following

`ERRO[0048] Error parsing JSON response.: json: cannot unmarshal object into Go value of type string`

I then tried commenting out the following line `IMAGE_FEATURES_append = " read-only-rootfs"` on the tegra-demo.conf layer and rebake the image in an attempt to make the / folder writable which didn't work.

Now I think I am out of ideas.

**Comment by dwalkes** [comment]
@ACAVJW4H this would probably be a better question for hub.mender.com but there's a help section on your hosted.mender.io instance at https://hosted.mender.io/ui/#/help/system-updates/build-with-yocto which is useful here to 
 see how to switch from the demo layer and update your server URL and tenant token.

**Comment by ACAVJW4H** [comment]
Thanks, I was finally able to see my device on the dashboard!
