### ISSUE TITLE
Jetson Orin Nano 4GB (P3767-0004) unable to access the system

### ISSUE THREAD

**Issue by Oats-max** [OE4T/tegra-demo-distro#270]
Device info:
![image](https://github.com/OE4T/tegra-demo-distro/assets/61582001/94247c6a-74b0-4e4d-8b0a-ace038b44332)
tegra-demo-distro branch:
kirkstone
 source ../setup-env --machine p3768-0000-p3767-0004
 When I compile it successfully,and executed successfully with doflash.sh,Unable to access the system,Did I use the wrong step?
<img width="1437" alt="image" src="https://github.com/OE4T/tegra-demo-distro/assets/61582001/80edad2e-5a5d-4196-bb74-d40247257c7e">

**Comment by dwalkes** [comment]
> executed successfully with doflash.sh

Are you using [initrd-flashing](https://github.com/OE4T/meta-tegra/wiki/initrd-flashing-support)?  I'd expect that to be required on the nano.

You may need to check the notes there about verifying boot order in UEFI as well.

**Comment by Oats-max** [comment]
Yes, I tried,Is it necessary to add TNSPEC_BOOTDEV:p3768-0000-p3767-0004 = "nvme0n1p1" to the compilation?
<img width="821" alt="image" src="https://github.com/OE4T/tegra-demo-distro/assets/61582001/bb426c7c-7ce9-4e18-b589-052e0e238723">
