### ISSUE TITLE
upgrade from dunfell-l4t-r32.4.3 to dunfell-l4t-r32.6.1 via mender failed

### ISSUE THREAD

**Issue by damgot** [OE4T/tegra-demo-distro#276]
Hello,

I have multiple Jetson Nano devices running a custom image based on the demo-image-base from the dunfell-l4t-r32.4.3 branch.

I would like to upgrade these Jetson devices to L4T 32.6.1 through Mender. I have successfully built an image based on the dunfell-l4t-r32.6.1 branch and deployed this new image on a Jetson via Mender. 
However, when the Jetson boots, it fails and boots to the old 32.4.3 version.

I have read that U-Boot was moved to QSPI after the r32.5.1 version, but I am using an SD card. Maybe my issue is related to this.

Can you tell me if this OTA upgrade is possible ? If yes, how can I do it ?

Thanks.

**Comment by madisongh** [comment]
It is technically possible to do, but not using a normal Mender OTA artifact, due to the changes in the boot firmware between those versions.  See [this wiki page](https://github.com/OE4T/meta-tegra/wiki/Over-the-air-reflashing-process) for some information on the topic.
